# Generated by Django 2.2.24 on 2021-08-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_goals', '0004_auto_20210806_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'course_key'], name='course_goal_user_id_4edecc_idx'),
        ),
    ]
